import * as fs from 'node:fs'
import * as path from 'node:path'

import { cli, command } from 'cleye'

import { compareLocaleKeys } from './locale-utils.ts'

function extractKeys(content: string): Set<string> {
  const keys = new Set<string>()
  const regex = /^([a-zA-Z][a-zA-Z0-9_-]*)\s*=/gm
  let match

  while ((match = regex.exec(content)) !== null) {
    const key = match[1]
    if (key) keys.add(key)
  }

  return keys
}

function loadLocaleKeys(dir: string): Map<string, Set<string>> {
  const result = new Map<string, Set<string>>()
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.ftl'))

  for (const file of files) {
    const locale = file.slice(0, -4)
    const content = fs.readFileSync(path.join(dir, file), 'utf-8')
    result.set(locale, extractKeys(content))
  }

  return result
}

function extractMessageVars(content: string): Map<string, string[]> {
  const result = new Map<string, string[]>()
  const varPattern = /\$([a-zA-Z][a-zA-Z0-9_-]*)/g

  let currentKey: string | null = null
  let currentBody = ''

  const flush = () => {
    if (!currentKey) return

    const vars: string[] = []
    varPattern.lastIndex = 0
    let match

    while ((match = varPattern.exec(currentBody)) !== null) {
      const v = match[1]
      if (v && !vars.includes(v)) vars.push(v)
    }

    if (vars.length > 0) {
      result.set(currentKey, vars)
    }

    currentKey = null
    currentBody = ''
  }

  for (const line of content.split('\n')) {
    const topLevel = /^([a-zA-Z][a-zA-Z0-9_-]*)\s*=(.*)/.exec(line)

    if (topLevel) {
      flush()
      currentKey = topLevel[1] ?? null
      currentBody = topLevel[2] ?? ''
    } else if (currentKey) {
      currentBody += '\n' + line
    }
  }

  flush()

  return result
}

function extractCommands(keys: Set<string>): string[] {
  const commands: string[] = []

  for (const key of keys) {
    if (key.endsWith('-description')) {
      const command = key.slice(0, -'-description'.length)

      if (!command.includes('-') || isTopLevelCommand(command, keys)) {
        commands.push(command)
      }
    }
  }

  return commands.sort()
}

function isTopLevelCommand(candidate: string, keys: Set<string>): boolean {
  const parts = candidate.split('-')

  for (let i = 1; i < parts.length; i++) {
    const prefix = parts.slice(0, i).join('-')

    if (keys.has(`${prefix}-description`)) {
      return false
    }
  }

  return true
}

function generateTypes(dir: string, out: string, defaultLocale: string, moduleName: string): void {
  const translations = loadLocaleKeys(dir)
  const defaultKeys = translations.get(defaultLocale)

  if (!defaultKeys) {
    console.error(`Default locale "${defaultLocale}" not found in ${dir}`)
    process.exit(1)
  }

  const ftlContent = fs.readFileSync(path.join(dir, `${defaultLocale}.ftl`), 'utf-8')
  const messageVars = extractMessageVars(ftlContent)

  const commands = extractCommands(defaultKeys)
  const sortedKeys = [...defaultKeys].sort()

  const commandsUnion = commands.map((c) => `"${c}"`).join(' | ') || 'never'
  const keysUnion = sortedKeys.map((k) => `"${k}"`).join('\n      | ') || 'never'

  const argsEntries = [...messageVars.entries()]
    .filter(([key]) => defaultKeys.has(key))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, vars]) => `      '${key}': { ${vars.map((v) => `${v}: string | number`).join('; ')} }`)

  const lines = [
    '// Auto-generated by @argon-sdk/locales CLI — do not edit',
    '',
    `declare module '${moduleName}' {`,
    '  interface LocaleKeyRegistry {',
    `    commands: ${commandsUnion}`,
    `    keys:`,
    `      | ${keysUnion}`,
  ]

  if (argsEntries.length > 0) {
    lines.push('    args: {')
    for (const entry of argsEntries) {
      lines.push(entry)
    }
    lines.push('    }')
  }

  lines.push('  }', '}', '', 'export {}', '')

  fs.writeFileSync(out, lines.join('\n'), 'utf-8')
  console.log(`Generated ${path.relative(process.cwd(), out)}`)
  console.log(`  ${commands.length} command(s): ${commands.join(', ')}`)
  console.log(`  ${sortedKeys.length} key(s) total`)
}

function checkLocales(dir: string, defaultLocale: string): void {
  const translations = loadLocaleKeys(dir)
  const defaultKeys = translations.get(defaultLocale)

  if (!defaultKeys) {
    console.error(`Default locale "${defaultLocale}" not found in ${dir}`)
    process.exit(1)
  }

  let hasIssues = false

  for (const [locale, keys] of translations) {
    if (locale === defaultLocale) {
      continue
    }

    const { missing, extra } = compareLocaleKeys(defaultKeys, keys)

    const unexpectedExtra = extra.filter((key) => !key.endsWith('-name') || defaultKeys.has(key))

    if (missing.length === 0 && unexpectedExtra.length === 0) {
      continue
    }

    hasIssues = true

    if (missing.length > 0) {
      console.log(`${locale}: ${missing.length} missing key(s)`)

      for (const key of missing) {
        console.log(`  - ${key}`)
      }
    }

    if (unexpectedExtra.length > 0) {
      console.log(`${locale}: ${unexpectedExtra.length} extra key(s)`)

      for (const key of unexpectedExtra) {
        console.log(`  + ${key}`)
      }
    }
  }

  if (hasIssues) {
    process.exit(1)
  }
}

function watchDirectory(dir: string, callback: () => void): void {
  let debounceTimer: ReturnType<typeof setTimeout> | null = null

  console.log(`Watching ${dir} for changes...`)

  fs.watch(dir, (_eventType, filename) => {
    if (!filename?.endsWith('.ftl')) {
      return
    }

    if (debounceTimer) {
      clearTimeout(debounceTimer)
    }

    debounceTimer = setTimeout(() => {
      console.log(`\nChanged: ${filename}`)
      callback()
    }, 100)
  })
}

const sharedFlags = {
  dir: {
    type: String,
    description: 'Directory with .ftl files',
  },
  defaultLocale: {
    type: String,
    description: 'Default locale code',
    default: 'en',
  },
  watch: {
    type: Boolean,
    alias: 'w',
    description: 'Watch for changes and re-run automatically',
  },
} as const

function requireDir(dir: string | undefined): asserts dir is string {
  if (!dir) {
    console.error('Missing --dir <path>')
    process.exit(1)
  }
}

const genCommand = command({
  name: 'gen',
  help: { description: 'Generate TypeScript type definitions from .ftl files' },
  flags: {
    ...sharedFlags,
    out: {
      type: String,
      description: 'Output file path (default: <dir>/locale-keys.d.ts)',
    },
    module: {
      type: String,
      description: 'Module name for augmentation',
      default: '@argon-sdk/locales',
    },
  },
}, (argv) => {
  const { dir, defaultLocale, watch, out, module: moduleName } = argv.flags

  requireDir(dir)

  const resolvedDir = path.resolve(dir)
  const resolvedOut = path.resolve(out ?? path.join(resolvedDir, 'locale-keys.d.ts'))

  generateTypes(resolvedDir, resolvedOut, defaultLocale, moduleName)

  if (watch) {
    watchDirectory(resolvedDir, () => {
      generateTypes(resolvedDir, resolvedOut, defaultLocale, moduleName)
    })
  }
})

const checkCommand = command({
  name: 'check',
  help: { description: 'Check locale files for missing or extra keys' },
  flags: sharedFlags,
}, (argv) => {
  const { dir, defaultLocale, watch } = argv.flags

  requireDir(dir)

  const resolvedDir = path.resolve(dir)

  checkLocales(resolvedDir, defaultLocale)

  if (watch) {
    watchDirectory(resolvedDir, () => {
      checkLocales(resolvedDir, defaultLocale)
    })
  }
})

cli({
  name: 'argon-locales',
  commands: [genCommand, checkCommand],
})
